# fly.toml app configuration file generated for anhleapp on 2023-10-08T06:05:12+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anhleapp"
primary_region = "sin"

[build]
  image = "anhlh9/anhleapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloundName="dcf5ztjf1"
  CloudinarySettings__ApiKey="796531891419714"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
